apiVersion: v1
kind: Service
metadata:
  name: echo-server
spec:
  type: {{ .Values.service.type }}
  selector:
    app: echo-server
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80